doctrine:
  dbal:
    driver:   pdo_mysql
    url: 'mysql://root:admin@db:3307/prooph-example'
    charset:  UTF8
    server_version: '5.7'
    mapping_types:
      enum: string
  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    mappings:
      Projections:
        is_bundle: false
        type: yml
        dir: '%kernel.project_dir%/config/mapping/orm/projections'
        prefix: 'App\Infrastructure'
        alias: Projections
