services:

  _defaults:
    autowire: true
    autoconfigure: false
    public: false

  _instanceof:
    App\Infrastructure\Common\CommandHandler\CommandHandlerInterface:
      public: true
      tags: ['app.command_handler']

    App\Infrastructure\Common\QueryHandler\QueryHandlerInterface:
      public: true
      tags: ['app.query']

  App\Application\Command\Category\Create\CreateCategoryHandler:
    public: true

  App\Infrastructure\Common\CommandHandler\CommandBus:
    public: true

  App\Infrastructure\Common\QueryHandler\QueryBus:
    public: true

