services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $aggregateTranslator: '@prooph_event_sourcing.aggregate_translator'

  _instanceof:
    App\Infrastructure\Common\CommandHandler\CommandHandlerInterface:
      tags: ['app.command_handler']

    App\Infrastructure\Common\QueryHandler\QueryHandlerInterface:
      tags: ['app.query']

    Prooph\EventStore\Projection\AbstractReadModel:
      public: true

    Prooph\Bundle\EventStore\Projection\ReadModelProjection:
      public: true

    Prooph\EventSourcing\Aggregate\AggregateRepository:
      public: true




  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  App\Infrastructure\Common\CommandHandler\CommandBus:
    public: true

  App\Infrastructure\Category\Repository\CategoryStoreRepository: ~

  App\Infrastructure\Author\Repository\AuthorStoreRepository: ~

  App\Infrastructure\Common\QueryHandler\QueryBus:
    public: true

  App\Infrastructure\Category\Projection\CategoryReadModel:
    public: true

  Prooph\EventStore\EventStore:
    alias: 'Prooph\EventStore\Pdo\MySqlEventStore'
    public: true

  Prooph\EventStore\ReadOnlyEventStore:
    alias: 'Prooph\EventStore\Pdo\MySqlEventStore'
    public: true

  Prooph\Common\Messaging\MessageFactory:
    alias: 'prooph_service_bus.message_factory'
    public: true