services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $aggregateTranslator: '@prooph_event_sourcing.aggregate_translator'

  _instanceof:
    App\Infrastructure\Common\CommandHandler\CommandHandlerInterface:
      tags: ['app.command_handler']

    App\Infrastructure\Common\QueryHandler\QueryHandlerInterface:
      tags: ['app.query']

    Prooph\EventStore\Projection\AbstractReadModel:
      public: true

    Prooph\Bundle\EventStore\Projection\ReadModelProjection:
      public: true



  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  App\Infrastructure\Common\CommandHandler\CommandBus:
    public: true

  App\Infrastructure\Category\Repository\CategoryStoreRepository: ~

  App\Infrastructure\Common\QueryHandler\QueryBus:
    public: true

